import { AGENT_WORKFLOW_PATHS, type AgentKind } from "./contracts.js";
import { inspectProvenance, stampProvenance } from "./provenance.js";
import {
  type CredentialKind,
  type PinnedAction,
  renderAgentWorkflow,
} from "./templates.js";

export type PlannedAction =
  | { kind: "create"; path: string; contents: string }
  | { kind: "update"; path: string; contents: string }
  | { kind: "delete"; path: string; reason: string }
  | { kind: "unchanged"; path: string }
  | { kind: "conflict"; path: string; reason: string };

export type ReconcileInput = {
  /** The agent the caller is selecting. Overrides whatever the config currently says. */
  agent: AgentKind;
  credential: CredentialKind;
  botLogin: string;
  label: string;
  checkoutAction: PinnedAction;
  agentAction: PinnedAction;
  uploadArtifactAction: PinnedAction;
  /** Current contents of every managed path that exists, keyed by repository path. */
  existing: ReadonlyMap<string, string>;
  force: boolean;
};

export type ReconcilePlan = {
  actions: readonly PlannedAction[];
  /** True when nothing needs to change. */
  clean: boolean;
  /** True when a hand-edited managed file blocks the plan. */
  blocked: boolean;
};

export function managedPaths(): readonly string[] {
  return [AGENT_WORKFLOW_PATHS.claude, AGENT_WORKFLOW_PATHS.codex];
}

function planFile(
  path: string,
  desired: string,
  existing: ReadonlyMap<string, string>,
  force: boolean,
): PlannedAction {
  const current = existing.get(path);
  if (current === undefined) {
    return { kind: "create", path, contents: desired };
  }
  if (current === desired) {
    return { kind: "unchanged", path };
  }
  const state = inspectProvenance(current);
  if (state !== "managed" && !force) {
    return {
      kind: "conflict",
      path,
      reason: state === "modified"
        ? "the file has been edited since it was generated"
        : "the file was not generated by this tool",
    };
  }
  return { kind: "update", path, contents: desired };
}

/**
 * Computes the whole desired file set and diffs it against what is committed, rather
 * than applying imperative steps per scenario.
 *
 * The switch case is why: changing agent must write the new workflow and delete the old
 * one together. A stale workflow left behind still matches the actor and label guard, so
 * two agents would act on the same issue and open competing pull requests against two
 * different bills.
 */
export function planRepositoryAgentFiles(input: ReconcileInput): ReconcilePlan {
  const actions: PlannedAction[] = [
    planFile(
      AGENT_WORKFLOW_PATHS[input.agent],
      stampProvenance(renderAgentWorkflow({
        agent: input.agent,
        credential: input.credential,
        botLogin: input.botLogin,
        label: input.label,
        checkoutAction: input.checkoutAction,
        agentAction: input.agentAction,
        uploadArtifactAction: input.uploadArtifactAction,
      })),
      input.existing,
      input.force,
    ),
  ];

  for (const [agent, path] of Object.entries(AGENT_WORKFLOW_PATHS)) {
    if (agent === input.agent || !input.existing.has(path)) {
      continue;
    }
    actions.push({
      kind: "delete",
      path,
      reason: `this repository now uses '${input.agent}', and this workflow would ` +
        "still run on the same issue",
    });
  }

  return {
    actions,
    clean: actions.every((action) => action.kind === "unchanged"),
    blocked: actions.some((action) => action.kind === "conflict"),
  };
}
